CREATE  database novacart;
USE novacart;

CREATE TABLE orders(
order_id VARCHAR (50),
order_date DATE,
customer_id VARCHAR(50),
customer_name VARCHAR(255),
product_id VARCHAR(50),
product_name VARCHAR(255),
category VARCHAR(100),
region VARCHAR(100),
quantity INT,
sales DECIMAL(12,2),
cost DECIMAL(12,2),
discount_pct DECIMAL(5,2),
recognized DECIMAL(12,2),
profit DECIMAL(12,2),
payment_method VARCHAR(100),
order_status VARCHAR(50)
);

RENAME TABLE novacart_info TO novacart_orders;
select count(*) as total _rows
from novacart_orders;

select count(*) as rows_with_cust_name
from novacart_orders
where customer_name IS NOT NULL;

select count(*) as rows_without_cust_name
from novacart_orders
where customer_name IS  NULL;

Select MIN(order_id) as first_order,
   MAX(order_id) as second_order,
   COUNT(DISTINCT order_id) as unique_orders
from novacart_orders;

# top 10 orders
select*
from novacart_orders
order by order_id
limit 10;

#find total orders
select count(order_id) as total_orders
from novacart_orders;

#find all orders from electronic category
select category,count(order_id) as total_orders
from novacart_orders
group by category
having category='Electronics';

1. what is the total revenue generated by novacart and what is the total profit.
select SUM(sales) as total_revenue,
SUM(profit) as total_profit
from novacart_orders;


2.Which product category generates the highest sales
select category,sum(sales) as total_sales
from novacart_orders
group by category
order by total_sales desc
limit 1;

3.which regions generate the highest profit?
select region,sum(profit) as total_profit
from novacart_orders
group by region
order by total_profit desc
limit 1;

4.what are the top 10 customer by total sales?
select customer_name,SUM(sales) as total_sales
from novacart_orders
group by customer_name
order by total_sales desc
limit 10;

5.which 10 products generate the highest profit?
select product_name,SUM(profit) as total_profit
from novacart_orders
group by product_name
order by total_profit
limit 10;

6.what percentage of order are completed,returned,and cancelled?
SELECT
    order_status,
    COUNT(*) AS order_count,
    ROUND(COUNT(*) * 100.0 / (SELECT COUNT(*) FROM novacart_orders), 2) AS percentage
FROM novacart_orders
GROUP BY order_status
ORDER BY percentage DESC;



7.which payment is used most frequently by customers
select payment_method,Count(payment_method) as payment_count
from novacart_orders
group by payment_method
order by payment_count desc
limit 1;


8.which product category has the highest average profit per order?
select category ,avg(profit) as avg_profit
from novacart_orders
group by category
order by avg_profit desc
limit 1;

9.which category performs best in each region?
select region,category,sum(sales) as total_sales
from novacart_orders
group by region,category
order by total_sales desc;

10.which category has the highest return rate?
Select
    category,
    COUNT(CASE WHEN order_status = 'Returned' THEN 1 END) * 100.0
        / COUNT(*) AS return_rate
from novacart_orders
group by category
order by return_rate DESC;

11.how have sales and profit changed month over month
Select
    DATE_FORMAT(order_date, '%Y-%m') AS month,
    SUM(sales) AS total_sales,
    SUM(profit) AS total_profit
from novacart_orders
group by DATE_FORMAT(order_date, '%Y-%m')
order by month;

12.which 10 customer generates the highest total profit for novacart?
Select customer_name,SUM(profit) AS total_profit
from novacart_orders
group by customer_name
order by total_profit desc
limit 10;


13.what is Novacart overall profit margin?
  Select
    ROUND(SUM(profit) * 100.0 / SUM(sales), 2) AS overall_profit_margin
   from novacart_orders;
   
 14. Which categories have the highest profit margin?
 Select 
 category,
  ROUND(SUM(profit)*100.0 / SUM(sales),2) AS overall_profit_margin
  from novacart_orders
  group by category
  order by overall_profit_margin desc
  limit 1;
  
  15.Which products have high sales but low profit margins?
  WITH product_metrics AS (
    SELECT
        product_name,
        SUM(sales) AS total_sales,
        SUM(profit) AS total_profit,
        SUM(profit) * 100.0 / SUM(sales) AS profit_margin
    FROM novacart_orders
    GROUP BY product_name
)
SELECT *
FROM product_metrics
ORDER BY total_sales DESC;

16.Which products are generating losses?
  select product_name,SUM(sales) as total_sales ,SUM(profit) as total_profit
  from novacart_orders
  group by product_name
  having SUM(sales)<0
  order by total_sales asc;
  
  17.What is the average order value (AOV)?
   SELECT 
    ROUND(
        SUM(sales) / COUNT(DISTINCT order_id),
        2
    ) AS average_order_value
FROM novacart_orders;
  
  18.Which region has the highest average order value?
  SELECT
    region,
    ROUND(
        SUM(sales) / COUNT(DISTINCT order_id),
        2
    ) AS average_order_value
FROM novacart_orders
GROUP BY region
ORDER BY average_order_value DESC;

19.What percentage of customers are repeat customers?
WITH customer_orders AS (
    SELECT
        customer_id,
        COUNT(DISTINCT order_id) AS total_orders
    FROM novacart_orders
    GROUP BY customer_id
)
SELECT
    ROUND(
        SUM(CASE WHEN total_orders > 1 THEN 1 ELSE 0 END)
        * 100.0 / COUNT(*),
        2
    ) AS repeat_customer_percentage
FROM customer_orders;

20.Which months have the highest sales growth?
WITH monthly_sales AS (
    SELECT
        DATE_FORMAT(order_date, '%Y-%m') AS month,
        SUM(sales) AS total_sales
    FROM novacart_orders
    GROUP BY DATE_FORMAT(order_date, '%Y-%m')
),
monthly_comparison AS (
    SELECT
        month,
        total_sales,
        LAG(total_sales) OVER (ORDER BY month) AS previous_month_sales
    FROM monthly_sales
)
SELECT
    month,
    total_sales,
    previous_month_sales,
    ROUND(
        (total_sales - previous_month_sales)
        * 100.0 / previous_month_sales,
        2
    ) AS mom_growth_pct
FROM monthly_comparison
ORDER BY month;